# Generated by Django 5.1.3 on 2024-12-05 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroTratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tratamientos', to='citas.registro')),
                ('id_tratamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citas.tratamiento')),
            ],
            options={
                'unique_together': {('id_registro', 'id_tratamiento')},
            },
        ),
    ]
