# Generated by Django 5.1.3 on 2024-12-05 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='alergiass',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='enfermedadess',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
