# Generated by Django 5.1.3 on 2024-12-05 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0004_alter_cita_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='es_admin',
            field=models.BooleanField(default=False),
        ),
    ]
