# Generated by Django 5.0.6 on 2024-11-15 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0009_tratamiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='TratamientoEnfermedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_enfermedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citas.enfermedad')),
                ('id_tratamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citas.tratamiento')),
            ],
            options={
                'unique_together': {('id_tratamiento', 'id_enfermedad')},
            },
        ),
    ]
