# Generated by Django 5.0.6 on 2024-11-15 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0010_tratamientoenfermedad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('marca', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
            ],
        ),
    ]
