# Generated by Django 5.0.6 on 2024-11-15 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0011_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citas.producto')),
                ('id_registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citas.registro')),
            ],
            options={
                'unique_together': {('id_registro', 'id_producto')},
            },
        ),
    ]
